apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-news

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - elasticsearch-deployment.yaml
  - backend-deployment.yaml
  - ml-service-deployment.yaml
  - frontend-deployment.yaml
  - scraper-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: smart-news-aggregator
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
